name: todos_repository
description: A respository that handles todo releated requests.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  todos_api:
    path: ../todos_api

dev_dependencies:
  mocktail: ^0.2.0
  test: ^1.17.0
  very_good_analysis: ^2.4.0